export default {
  gmail: {
    id: 0,
    name: '',
    email: '',
    type: 'gmail',
    username: '',
    emailsPerDayLimit: 200,
    sendingClientType: 0,
    isLimitEmailPerMinute: false,
    emailsPerMinuteLimit: 30,
    emailsThrottleMinuteAmount: 1,
    signature: '',
    isOptOutLinkEnabled: false,
    useDifferentEmailServers: false,
    useDifferentAccountName: false,
    optOutTextBlock:
      "PS: If you don't want to hear from me anymore, just let me know",
    optOutPageText: 'You now have been removed from my contact list.',
    imapSettings: {
      username: '',
      host: 'imap.gmail.com',
      port: 993,
      password: '',
      enableSsl: true,
    },
    smtpSettings: {
      username: '',
      senderName: '',
      replyToEmail: '',
      host: 'smtp.gmail.com',
      port: 465,
      password: '',
      enableSsl: true,
    },
  },
  outlook: {
    id: 0,
    name: '',
    email: '',
    type: 'outlook',
    username: '',
    emailsPerDayLimit: 200,
    sendingClientType: 1,
    isLimitEmailPerMinute: false,
    emailsPerMinuteLimit: 30,
    emailsThrottleMinuteAmount: 1,
    signature: '',
    isOptOutLinkEnabled: false,
    useDifferentEmailServers: false,
    useDifferentAccountName: false,
    optOutTextBlock:
      "PS: If you don't want to hear from me anymore, just let me know",
    optOutPageText: 'You now have been removed from my contact list.',
    imapSettings: {
      username: '',
      host: 'outlook.office365.com',
      port: 993,
      password: '',
      enableSsl: true,
    },
    smtpSettings: {
      username: '',
      senderName: '',
      replyToEmail: '',
      host: 'smtp.office365.com',
      port: 587,
      password: '',
      enableSsl: false,
    },
  },
  exchange: {
    id: 0,
    name: '',
    email: '',
    type: 'exchange',
    username: '',
    emailsPerDayLimit: 200,
    sendingClientType: 1,
    isLimitEmailPerMinute: false,
    emailsPerMinuteLimit: 30,
    emailsThrottleMinuteAmount: 1,
    signature: '',
    isOptOutLinkEnabled: false,
    useDifferentEmailServers: false,
    useDifferentAccountName: false,
    optOutTextBlock:
      "PS: If you don't want to hear from me anymore, just let me know",
    optOutPageText: 'You now have been removed from my contact list.',
    imapSettings: {
      username: '',
      host: 'outlook.office365.com',
      port: 993,
      password: '',
      enableSsl: true,
    },
    smtpSettings: {
      username: '',
      senderName: '',
      replyToEmail: '',
      host: 'smtp.office365.com',
      port: 587,
      password: '',
      enableSsl: false,
    },
  },
  other: {
    id: 0,
    name: '',
    email: '',
    type: 'other',
    username: '',
    emailsPerDayLimit: 200,
    sendingClientType: 1,
    isLimitEmailPerMinute: false,
    emailsPerMinuteLimit: 30,
    emailsThrottleMinuteAmount: 1,
    signature: '',
    isOptOutLinkEnabled: false,
    useDifferentEmailServers: false,
    useDifferentAccountName: false,
    optOutTextBlock:
      "PS: If you don't want to hear from me anymore, just let me know",
    optOutPageText: 'You now have been removed from my contact list.',
    imapSettings: {
      username: '',
      host: '',
      port: 993,
      password: '',
      enableSsl: true,
    },
    smtpSettings: {
      username: '',
      senderName: '',
      replyToEmail: '',
      host: '',
      port: 587,
      password: '',
      enableSsl: true,
    },
  },
}
