export default [
  {
    name: 'newsletter',
    title: 'Newsletter',
    description: "Capture visitor's email for our monthly Newsletter",
    icon: 'envelop-open',
    fields: [
      {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholderText: 'name@example.com',
        required: true,
      },
    ],
    submitButtonText: 'Submit',
  },
  {
    name: 'newsletter2',
    title: 'Newsletter 2',
    description: "Capture visitor's name and email for our monthly Newsletter",
    icon: 'envelop-open',
    fields: [
      {
        name: 'first_name',
        label: 'First name',
        type: 'text',
        placeholderText: 'Joe',
        required: false,
      },
      {
        name: 'last_name',
        label: 'Last name',
        type: 'text',
        placeholderText: 'Doe',
        required: false,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholderText: 'name@example.com',
        required: true,
      },
      {
        name: 'email_opt_in',
        label: 'I want to receive emails from SITE_NAME',
        type: 'checkbox',
        placeholderText: '',
        required: false,
      },
    ],
    submitButtonText: 'Join Newsletter',
  },
  {
    name: 'contact',
    title: 'Contact',
    description: "Capture visitor's details to contact them later",
    icon: 'user-id',
    fields: [
      {
        name: 'first_name',
        label: 'First name',
        type: 'text',
        placeholderText: 'Joe',
        required: false,
      },
      {
        name: 'last_name',
        label: 'Last name',
        type: 'text',
        placeholderText: 'Doe',
        required: false,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholderText: 'name@example.com',
        required: true,
      },
      {
        name: 'phone',
        label: 'Phone number',
        type: 'text',
        placeholderText: '081234567890',
        required: false,
      },
    ],
    submitButtonText: 'Add Details',
  },
  {
    name: 'book-a-demo',
    title: 'Book a demo',
    description: "Capture visitor's details for our product demo",
    icon: 'display',
    fields: [
      {
        name: 'first_name',
        label: 'First name',
        type: 'text',
        placeholderText: 'Joe',
        required: false,
      },
      {
        name: 'last_name',
        label: 'Last name',
        type: 'text',
        placeholderText: 'Doe',
        required: false,
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        placeholderText: 'Comp Inc.',
        required: true,
      },
      {
        name: 'phone',
        label: 'Phone number',
        type: 'text',
        placeholderText: '081234567890',
        required: false,
      },
      {
        name: 'interested_feature',
        label: 'Which product would you like a Demo of?',
        type: 'text',
        placeholderText: 'Clientforce Forms',
        required: false,
      },
    ],
    submitButtonText: 'Book Demo',
  },
  {
    name: 'waitlist',
    title: 'Waitlist',
    description: "Capture visitor's email for our waitlist",
    icon: 'notes',
    fields: [
      {
        name: 'first_name',
        label: 'First name',
        type: 'text',
        placeholderText: 'Joe',
        required: false,
      },
      {
        name: 'last_name',
        label: 'Last name',
        type: 'text',
        placeholderText: 'Doe',
        required: false,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholderText: 'name@example.com',
        required: true,
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        placeholderText: 'Comp Inc.',
        required: false,
      },
      {
        name: 'email_opt_in',
        label: 'I want to receive emails from SITE_NAME',
        type: 'checkbox',
        placeholderText: '',
        required: false,
      },
    ],
    submitButtonText: 'Add me to waitlist',
  },
  {
    name: 'custom',
    title: 'Custom',
    description: "Capture visitor's email for our monthly Newsletter",
    icon: 'ruler-pen',
    fields: [
      {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholderText: 'name@example.com',
        required: true,
      },
    ],
    submitButtonText: 'Submit',
  },
]
